installer updates

diff --git a/tz-bot-installer b/tz-bot-installer
--- a/tz-bot-installer
+++ b/tz-bot-installer
@@ -1,4 +1,11 @@
 sudo curl -L https://github.com/janniktaulan/lego-testing/releases/download/beta/tz-lego.sh > /tmp/tz-bot
 sudo mkdir -p /usr/local/bin
-sudo mv /tmp/tz-bot /usr/local/bin/tz-bot
-sudo chmod +x /usr/local/bin/tz-bot
+if sudo mv /tmp/tz-bot /usr/local/bin/tz-bot; then
+    sudo chmod +x /usr/local/bin/tz-bot
+    sudo curl -L https://github.com/janniktaulan/lego-testing/releases/download/beta/tz-bot-remover.sh > /etc/lego/tz-bot-remover.sh
+    sudo chmod +x /etc/lego/tz-bot-remover.sh
+    echo "TZ-Bot has been installed successfully. You can run it using the command 'tz-bot' or "sudo tz-bot"."
+else
+    echo "Installation failed."
+    exit 1
+fi
